### ISSUE TITLE
Custom templates not being generated on Nodebb 1.14.1

### ISSUE THREAD

**Issue by fais3000** [NodeBB-Community/nodebb-plugin-custom-pages#64]
- nodebb-plugin-custom-pages 1.2.0
- nodebb 1.14.1 is not able to generate custom tpl files defined in the plugin. 
- node: v10.14.2

When page is visited following error appears

```
node:16353) UnhandledPromiseRejectionWarning: Error: Failed to lookup view "free-online-chat-rooms" in views directory "/var/www/community/build/public/templates"
    at Function.render (/var/www/community/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/var/www/community/node_modules/express/lib/response.js:1012:7)
    at util.promisify (/var/www/community/src/middleware/render.js:61:83)
    at Promise (internal/util.js:275:30)
    at new Promise (<anonymous>)
    at internal/util.js:274:12
    at ServerResponse.renderOverride [as render] (/var/www/community/src/middleware/render.js:65:14)
(node:16353) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:16353) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

There are no errors on build similar to following
https://github.com/NodeBB/NodeBB/issues/5789

Reverting nodebb to 1.13.4-5 works.

**Comment by barisusakli** [comment]
Thanks for reporting I am taking a look at this.

**Comment by barisusakli** [comment]
Please try with v1.3.0 for this plugin.

**Comment by fais3000** [comment]
> Please try with v1.3.0 for this plugin.

@barisusakli Works now! Thanks for the quick fix.
